[options]
    # guifont = "SauceCodePro Nerd Font Mono:h11"
    guifont = "Knack Nerd Font:h14"

    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    colorscheme = "dracula"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    enable_vimfiler_welcome = false
    bootstrap_after = "myspacevim#after"

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "colorscheme"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "denite"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"

[[custom_plugins]]
name = "dracula/vim"
# merged = false # eh?
